# Generated by Django 5.1.3 on 2024-12-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("Search Standard", "Search Standard"),
                            ("Video Responsive", "Video Responsive"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdGroupStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("conversions", models.FloatField(default=0)),
                ("cost", models.FloatField(default=0)),
                ("date", models.DateField()),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("Desktop", "Desktop"),
                            ("Mobile", "Mobile"),
                            ("Tablet", "Tablet"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.adgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="adgroup",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.campaign",
            ),
        ),
    ]
