# Generated by Django 5.1.3 on 2024-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_adgroup_ad_group_id_unique_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="adgroupstats",
            name="ad_group_date_device_unique",
        ),
    ]
