# Generated by Django 5.1.4 on 2024-12-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_remove_adgroupstats_ad_group_date_device_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="adgroup",
            constraint=models.UniqueConstraint(
                fields=("name",), name="ad_group_name_unique"
            ),
        ),
    ]
