name: Code Coverage

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          ports: 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and run containers
        run: |
          docker compose up --build -d

      - name: Wait for PostgreSQL to be ready
        run: |
          TIMEOUT=60
          INTERVAL=2
          ELAPSED=0

          while [ $ELAPSED -lt $TIMEOUT ]; do
            if docker compose exec db pg_isready; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done

          if [ $ELAPSED -ge $TIMEOUT ]; then
            echo "PostgreSQL did not become ready within the timeout period."
            exit 1
          fi

      - name: Set up Docker
        run: |
          docker compose run app pytest --cov --cov-report=xml:/code/coverage.xml

      - name: Copy Coverage Report
        run: |
          docker compose cp app:/code/coverage.xml ./coverage.xml

      - name: Generate Coverage Summary
        id: coverage_summary
        run: |
          echo "## Code Coverage Summary" > coverage_summary.md
          docker compose exec app coverage report -m >> coverage_summary.txt || true
          docker compose cp app:/code/coverage_summary.txt ./coverage_summary.txt

      - name: Read Coverage Summary into Variable
        id: read_summary
        run: |
          echo "COVERAGE_SUMMARY<<EOF" >> $GITHUB_ENV
          cat coverage_summary.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR Comment with Coverage Results
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{env.COVERAGE_SUMMARY}}
          token: ${{ secrets.GITHUB_TOKEN }}
