name: Code Coverage

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=github_action_test" >> .env
          echo "POSTGRES_PASSWORD=github_action_test" >> .env
          echo "POSTGRES_DB=github_action_test" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and run containers
        run: |
          docker compose -f docker-compose-test.yml up --build -d

      - name: Wait for PostgreSQL to be ready
        run: |
          max_attempts=20
          attempt=0
          while [ $attempt -lt $max_attempts ]; do
            if docker compose -f docker-compose-test.yml exec -T db pg_isready -U github_action_test; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL... (attempt $((attempt+1)))"
            sleep 5
            attempt=$((attempt+1))
          done

          if [ $attempt -ge $max_attempts ]; then
            echo "PostgreSQL did not become ready within the timeout period."
            docker compose -f docker-compose-test.yml logs db
            exit 1
          fi

      - name: Build coverage file
        run: |
          docker compose -f docker-compose-test.yml run app pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Copy Coverage Report
        run: |
          docker compose -f docker-compose-test.yml cp app:/code/pytest.xml ./pytest.xml
          docker compose -f docker-compose-test.yml cp app:/code/pytest-coverage.txt ./pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Stop and remove containers
        if: success() || failure()
        run: docker compose down
