name: Code Coverage

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  DB_USER: github_action_test
  DB_PASSWORD: github_action_test
  DB_NAME: github_action_test
  DB_PORT: 5432
  DEBUG: "False"
  SECRET_KEY: example
  ALLOWED_HOSTS: localhost,127.0.0.1
  DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}"

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Print Environment Variables
        run: |
          echo "DEBUG=${DEBUG}"
          echo "ALLOWED_HOSTS=${ALLOWED_HOSTS}"
          echo "DATABASE_URL=${DATABASE_URL}"

      - name: Build image and run containers
        run: |
          docker compose up --build -d

      - name: Wait for PostgreSQL to be ready
        run: |
          TIMEOUT=60
          INTERVAL=2
          ELAPSED=0

          while [ $ELAPSED -lt $TIMEOUT ]; do
            if docker compose exec db pg_isready; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done

          if [ $ELAPSED -ge $TIMEOUT ]; then
            echo "PostgreSQL did not become ready within the timeout period."
            exit 1
          fi

      - name: Run migrations
        run: |
          docker compose run app python manage.py migrate --noinput

      - name: Build coverage file
        run: |
          docker compose run app pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=. | tee pytest-coverage.txt

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            pytest.xml
            pytest-coverage.txt
          retention-days: 5

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
