name: test-run

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            db:
                image: postgres:16-alpine
                env:
                    POSTGRES_HOST_AUTH_METHOD: trust
                    ports: 5432:5432
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build image and run containers
              run: |
                docker compose up --build -d

            - name: Run migrations
              run: |
                docker compose run app python manage.py migrate --noinput

            - name: Run tests
              run: |
                docker compose run app pytest .

            - name: Stop and remove containers
              if: success() || failure()
              run: docker compose down
