name: test-run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SECRET_KEY: github_action_test_secret_key
  DEBUG: "False"
  ALLOWED_HOSTS: localhost,127.0.0.1
  POSTGRES_DB: github_action_test
  POSTGRES_USER: github_action_test
  POSTGRES_PASSWORD: github_action_test
  DB_HOST: db
  DB_PORT: 5432
  DATABASE_URL: postgres://${POSTGRES_USER}:github_action_test@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker Compose version
        run: docker compose version

      - name: Print Environment Variables
        run: |
          echo "DEBUG=${DEBUG}"
          echo "ALLOWED_HOSTS=${ALLOWED_HOSTS}"
          echo "DATABASE_URL=${DATABASE_URL}"

      - name: Build image and run containers
        run: |
          docker compose up --build -d

      - name: Wait for PostgreSQL to be ready
        run: |
          TIMEOUT=60
          INTERVAL=2
          ELAPSED=0

          while [ $ELAPSED -lt $TIMEOUT ]; do
            if docker compose exec db pg_isready; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done

          if [ $ELAPSED -ge $TIMEOUT ]; then
            echo "PostgreSQL did not become ready within the timeout period."
            exit 1
          fi

      - name: Run migrations
        run: |
          docker compose run app python manage.py migrate --noinput

      - name: Run tests
        run: |
          docker compose run app pytest .

      - name: Stop and remove containers
        if: always()
        run: docker compose down
